/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package evaluator;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.junit.Test;

import java.io.File;
import java.io.InputStream;
import java.net.URL;

public class AppTest {
  @Test
  public void loadTemplate() throws Exception {
    URL testTemplateURL = this.getClass().getResource("/test_template.yaml");
    new App().loadTemplate(new File(testTemplateURL.toURI()));
  }

  @Test
  public void applyTemplate() throws Exception {
    try(InputStream testHTMLStream = this.getClass().getResourceAsStream("/test.html")) {
      String url = "https://www.mountainhardwear.com/mens-finder-rain-jacket-1572331.html?cgid=mens-jackets-rain&dwvar_1572331_variationColor=492#start=2";
      Document document = Jsoup.parse(
          testHTMLStream,
          "UTF-8",
          url);
      App app = new App();
      URL testTemplateURL = this.getClass().getResource("/test_template.yaml");
      Template template = app.loadTemplate(new File(testTemplateURL.toURI()));
      app.applyTemplate(url, template, document);
    }
  }
}
